# Generated by Django 4.0.6 on 2022-08-01 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Месяц',
                'verbose_name_plural': 'Месяцы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='blog.month', verbose_name='Месяц'),
            preserve_default=False,
        ),
    ]
