# Generated by Django 4.0.6 on 2022-08-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_month_post_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='month',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
